#! /usr/bin/env python
import zipfile
import shutil
import os
f = open('channels_profile', 'r');
while True:  
    line = f.readline().strip('\n')  
    if len(line) == 0:  
        break  
    else:  
        shutil.copy2('helloworld.apk', 'helloworld_' + line + '.apk')
        zipped = zipfile.ZipFile('helloworld_' + line + '.apk', 'a', zipfile.ZIP_DEFLATED) 
	empty_channel_file = "META-INF/mchannel_{channel}".format(channel=line)
	fp = open(line, 'w')
	zipped.write(os.path.basename(line), empty_channel_file)
	fp.close
	os.remove(line)
f.close()
    
